/** Exercises the real hook with in-memory collections; no Firebase/network access. */
import test from 'node:test'
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { build } from 'esbuild'
const require = createRequire(import.meta.url)
const mocks = {
  '@/contexts/AuthContext': 'export const useAuth = () => ({ userData: { role: "admin" } });',
  '@/hooks/use-firebase-collection': `export function useFirebaseCollection(name, constraints = []) {
    const fixture = globalThis.__revisionTestFixture;
    const archived = constraints.some(c => c?.[0] === 'statusLucrare' && c?.[1] === '==');
    return { data: name === 'lucrari' ? (archived ? [] : fixture.works) : fixture[name] || [], loading: false };
  }`,
  'firebase/firestore': `export const where = (...x) => x; export const orderBy = (...x) => x;
    export const limit = n => n; export const Timestamp = { fromDate: d => d };`,
}
const bundled = await build({
  stdin: { contents: `
    import React from 'react';
    import {renderToStaticMarkup} from 'react-dom/server';
    import {useDashboardStatus} from './hooks/use-dashboard-status';
    export function run(fixture, settings = {}) {
      globalThis.__revisionTestFixture = fixture;
      let result;
      function Probe() { result = useDashboardStatus({programatorReviziiEnabled:true,
        listateEnabled:true,listateRequireNoTechnicians:true,...settings}); return null; }
      renderToStaticMarkup(React.createElement(Probe));
      delete globalThis.__revisionTestFixture;
      return result;
    }
  `, resolveDir: process.cwd(), loader: 'tsx' },
  bundle: true, write: false, platform: 'node', format: 'cjs',
  external: ['react', 'react-dom/server'],
  plugins: [{ name: 'isolated-collections', setup(b) {
    b.onResolve({ filter: /.*/ }, args => mocks[args.path] ? { path: args.path, namespace: 'fixture' } : undefined)
    b.onLoad({ filter: /.*/, namespace: 'fixture' }, args => ({ contents: mocks[args.path], loader: 'js' }))
  } }],
})
const module = { exports: {} }
new Function('require', 'module', 'exports', bundled.outputFiles[0].text)(require, module, module.exports)
const { run } = module.exports
const base = { tipLucrare:'Revizie', autoGenerated:true, createdBy:'system', createdByName:'CRON Revizie',
  statusLucrare:'Listată', contract:'c', dataInterventie:'2026-09-18T09:00:00Z', tehnicieni:[] }
function fixture() {
  return { works:[
    {...base,id:'manual',autoGenerated:undefined,createdBy:'alin',createdByName:'Alin',locationId:'a',locatie:'A'},
    {...base,id:'auto-a',locationId:'a',locatie:'A'},
    {...base,id:'auto-b',locationId:'b',locatie:'B'},
  ], contracts:[{id:'c',number:'C1',revisionSchedulePreview:['a','b'].map(id=>({
    locationId:id,locationName:id.toUpperCase(),scheduledIso:'2026-09-18T09:00:00Z',generateIso:'2026-09-08T07:00:00Z'
  }))}], users:[{role:'tehnician',displayName:'Ion'}] }
}
test('real hook: automatic revisions have separate scheduler cards and manual revision stays listed', () => {
  const { buckets } = run(fixture())
  assert.deepEqual(buckets.listate.map(x=>x.id), ['manual'])
  assert.deepEqual(buckets.programatorRevizii.map(x=>[x.locatie,x.lucrareId]), [['A','auto-a'],['B','auto-b']])
  assert.equal(new Set(buckets.programatorRevizii.map(x=>x.id)).size, 2)
})
test('real hook: assignment removes only that location from scheduler and adds it to technician board', () => {
  const data=fixture(); data.works[1]={...data.works[1],tehnicieni:['Ion'],statusLucrare:'Atribuită'}
  const {buckets,personal}=run(data)
  assert.deepEqual(buckets.programatorRevizii.map(x=>x.lucrareId),['auto-b'])
  assert.deepEqual(buckets.listate.map(x=>x.id),['manual'])
  assert.deepEqual(personal.technicians.map(x=>[x.name,x.items.map(w=>w.id)]),[['Ion',['auto-a']]])
})
test('real hook: disabling technician filter never lists auto revisions; disabled scheduler does not leak them', () => {
  const {buckets}=run(fixture(),{listateRequireNoTechnicians:false,programatorReviziiEnabled:false})
  assert.deepEqual(buckets.listate.map(x=>x.id),['manual'])
  assert.deepEqual(buckets.programatorRevizii,[])
})
