import test from "node:test"
import assert from "node:assert/strict"
import { buildAutomaticRevisionIndex, findScheduledAutomaticRevision, isAutomaticRevision, isListedDashboardWork } from "./dashboard-revisions"

const automatic = {
  id: "auto-a", tipLucrare: "Revizie", autoGenerated: true,
  createdBy: "system", createdByName: "CRON Revizie", contractId: "contract-1",
  dataInterventie: "2026-09-18T10:00:00Z", locationId: "loc-a", locationName: "Locația A",
  statusLucrare: "Listată", tehnicieni: [] as string[],
}
const manual = { ...automatic, id: "manual", autoGenerated: undefined, createdBy: "admin-1", createdByName: "Alin" }
const schedule = { contractId: "contract-1", scheduledIso: "2026-09-18T00:00:00Z", locationId: "loc-a", locationName: "Locația A" }

test("only provenance marks revisions automatic; explicit false stays manual", () => {
  assert.equal(isAutomaticRevision(automatic), true)
  assert.equal(isAutomaticRevision({ ...automatic, autoGenerated: undefined }), true)
  assert.equal(isAutomaticRevision({ ...automatic, autoGenerated: false }), false)
  assert.equal(isAutomaticRevision(manual), false)
  assert.equal(isAutomaticRevision({ ...automatic, tipLucrare: "Intervenție" }), false)
  assert.equal(isAutomaticRevision({ ...manual, createdByName: "CRON Revizie" }), false)
})

test("automatic revisions never enter Listate, independent of technician setting", () => {
  for (const noTechnicians of [true, false]) {
    assert.equal(isListedDashboardWork(automatic, noTechnicians), false)
    assert.equal(isListedDashboardWork({ ...automatic, tehnicieni: ["Ion"] }, noTechnicians), false)
    assert.equal(isListedDashboardWork({ ...automatic, autoGenerated: undefined }, noTechnicians), false)
    assert.equal(isListedDashboardWork(manual, noTechnicians), true)
  }
})

test("manual tickets retain technician, archived and canceled rules", () => {
  assert.equal(isListedDashboardWork({ ...manual, tehnicieni: ["Ion"] }, true), false)
  assert.equal(isListedDashboardWork({ ...manual, tehnicieni: ["Ion"] }, false), true)
  assert.equal(isListedDashboardWork({ ...manual, statusLucrare: "Arhivată" }, false), false)
  assert.equal(isListedDashboardWork({ ...manual, statusLucrare: "Anulat" }, false), false)
  assert.equal(isListedDashboardWork({ ...manual, tipLucrare: "Intervenție" }, true), true)
  assert.equal(isListedDashboardWork({ ...manual, statusLucrare: "Amânată" }, true), true)
})

test("manual revision on same contract/day cannot replace automatic ticket", () => {
  const index = buildAutomaticRevisionIndex([manual, automatic])
  assert.equal(findScheduledAutomaticRevision(index, schedule)?.id, "auto-a")
  assert.equal(findScheduledAutomaticRevision(buildAutomaticRevisionIndex([manual]), schedule), undefined)
})

test("two locations on same contract/day navigate to distinct tickets, even with same names", () => {
  const second = { ...automatic, id: "auto-b", locationId: "loc-b" }
  const index = buildAutomaticRevisionIndex([automatic, second])
  assert.equal(findScheduledAutomaticRevision(index, schedule)?.id, "auto-a")
  assert.equal(findScheduledAutomaticRevision(index, { ...schedule, locationId: "loc-b" })?.id, "auto-b")
  assert.equal(findScheduledAutomaticRevision(index, { ...schedule, locationId: "loc-c" }), undefined)
})

test("legacy contract and location names are supported without guessing ambiguous locations", () => {
  const legacy = { ...automatic, contractId: undefined, contract: "contract-1", locationId: undefined, locationName: undefined, locatie: "Locația A" }
  assert.equal(findScheduledAutomaticRevision(buildAutomaticRevisionIndex([legacy]), schedule)?.id, "auto-a")
  const index = buildAutomaticRevisionIndex([automatic, { ...automatic, id: "auto-b", locationId: "loc-b" }])
  assert.equal(findScheduledAutomaticRevision(index, { ...schedule, locationId: undefined }), undefined)
})

test("legacy preview without IDs matches a unique current name but not another contract/day", () => {
  const index = buildAutomaticRevisionIndex([automatic])
  assert.equal(findScheduledAutomaticRevision(index, { ...schedule, locationId: undefined })?.id, "auto-a")
  assert.equal(findScheduledAutomaticRevision(index, { ...schedule, contractId: "other" }), undefined)
  assert.equal(findScheduledAutomaticRevision(index, { ...schedule, scheduledIso: "2026-09-19T00:00:00Z" }), undefined)
})

test("canceled automatic revisions cannot supply scheduler links", () => {
  const index = buildAutomaticRevisionIndex([{ ...automatic, statusLucrare: "Anulat" }])
  assert.equal(findScheduledAutomaticRevision(index, schedule), undefined)
})
