import { WORK_STATUS } from "@/lib/utils/constants"
import { toDateSafe } from "@/lib/utils/time-format"
import { isLucrareAnulata } from "@/lib/utils/work-canceled"

export interface RevisionDashboardWork {
  id?: string
  tipLucrare?: unknown
  autoGenerated?: unknown
  createdBy?: unknown
  createdByName?: string
  contractId?: unknown
  contract?: unknown
  dataInterventie?: unknown
  locationId?: unknown
  locationName?: unknown
  locatie?: unknown
  tehnicieni?: unknown
  statusLucrare?: string
}

const text = (value: unknown) => String(value ?? "").trim()

/** Proveniența, nu simpla existență a unui contract, separă reviziile automate. */
export function isAutomaticRevision(work: RevisionDashboardWork): boolean {
  if (text(work.tipLucrare).toLowerCase() !== "revizie") return false
  if (work.autoGenerated != null) return work.autoGenerated === true
  return text(work.createdBy) === "system" && text(work.createdByName) === "CRON Revizie"
}

/** Păstrează criteriile Listate existente, excluzând reviziile automate. */
export function isListedDashboardWork(work: RevisionDashboardWork, requireNoTechnicians: boolean): boolean {
  const technicians = Array.isArray(work.tehnicieni) ? work.tehnicieni : []
  return !isAutomaticRevision(work)
    && !isLucrareAnulata(work)
    && (!requireNoTechnicians || technicians.length === 0)
    && String(work.statusLucrare || "").toLowerCase() !== WORK_STATUS.ARCHIVED.toLowerCase()
}

function dateKey(value: unknown): string | null {
  if (typeof value === "string") {
    const iso = /^(\d{4}-\d{2}-\d{2})/.exec(value)
    if (iso) return iso[1]
  }
  const date = toDateSafe(value)
  if (!date || Number.isNaN(date.getTime())) return null
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`
}

export function buildAutomaticRevisionIndex<T extends RevisionDashboardWork>(works: readonly T[]) {
  const index = new Map<string, T[]>()
  for (const work of works) {
    if (!work.id || !isAutomaticRevision(work) || isLucrareAnulata(work)) continue
    const contract = text(work.contractId) || text(work.contract)
    const day = dateKey(work.dataInterventie)
    if (!contract || !day) continue
    const key = JSON.stringify([contract, day])
    index.set(key, [...(index.get(key) ?? []), work])
  }
  return index
}

/** ID-ul locației are prioritate; numele este fallback numai pentru datele vechi fără ID. */
export function findScheduledAutomaticRevision<T extends RevisionDashboardWork>(
  index: Map<string, T[]>,
  schedule: { contractId: string; scheduledIso?: unknown; locationId?: unknown; locationName?: unknown; location?: unknown },
): T | undefined {
  const day = dateKey(schedule.scheduledIso)
  if (!day) return undefined
  const candidates = index.get(JSON.stringify([text(schedule.contractId), day])) ?? []
  const locationId = text(schedule.locationId)
  const locationName = (text(schedule.locationName) || text(schedule.location)).toLowerCase()
  if (locationId) {
    const exact = candidates.find(work => text(work.locationId) === locationId)
    if (exact) return exact
  }
  const fallback = candidates.filter(work => {
    const workId = text(work.locationId)
    // Două ID-uri diferite nu devin aceeași locație dacă au același nume.
    if (locationId && workId) return false
    const workName = (text(work.locationName) || text(work.locatie)).toLowerCase()
    if (locationName || workName) return !!locationName && locationName === workName
    return !locationId && !workId
  })
  // Nu trimitem utilizatorul spre o locație aleasă arbitrar când datele sunt ambigue.
  return fallback.length === 1 ? fallback[0] : undefined
}
