/**
 * Diagnostic read-only: dump complet + istoric audit pentru revizii identificate după nrLucrare.
 *
 *   npx tsx scripts/inspect-revision-work-detail.ts 001829 001861 001833
 */

import fs from "node:fs"
import path from "node:path"
import process from "node:process"
import { initializeApp, cert, getApps } from "firebase-admin/app"
import { getFirestore } from "firebase-admin/firestore"

function loadDotEnv(filePath: string) {
  if (!fs.existsSync(filePath)) return
  const content = fs.readFileSync(filePath, "utf8")
  for (const line of content.split(/\r?\n/)) {
    if (!line || line.trim().startsWith("#")) continue
    const index = line.indexOf("=")
    if (index <= 0) continue
    const key = line.slice(0, index).trim()
    const raw = line.slice(index + 1).trim()
    if (!key || process.env[key]) continue
    process.env[key] = raw.replace(/^"|"$/g, "")
  }
}

loadDotEnv(path.resolve(process.cwd(), ".env"))

const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID
const clientEmail = process.env.FIREBASE_ADMIN_CLIENT_EMAIL
const privateKey = process.env.FIREBASE_ADMIN_PRIVATE_KEY?.replace(/\\n/g, "\n")

if (!projectId || !clientEmail || !privateKey) {
  console.error("Lipsesc NEXT_PUBLIC_FIREBASE_PROJECT_ID sau FIREBASE_ADMIN_* în .env")
  process.exit(1)
}

if (!getApps().length) {
  initializeApp({ credential: cert({ projectId, clientEmail, privateKey }), projectId })
}

const db = getFirestore()
const str = (v: any) => String(v ?? "").trim()
const wanted = process.argv.slice(2).filter((a) => !a.startsWith("--"))

async function main() {
  const snap = await db.collection("lucrari").where("tipLucrare", "==", "Revizie").get()
  const works = snap.docs
    .map((d) => ({ id: d.id, ...(d.data() as any) }))
    .filter((w) => wanted.some((n) => str(w.nrLucrare).includes(n)))

  for (const w of works) {
    console.log("\n==============================")
    console.log(
      JSON.stringify(
        {
          docId: w.id,
          nrLucrare: w.nrLucrare,
          locatie: w.locatie,
          locationId: w.locationId,
          dataEmiterii: w.dataEmiterii,
          dataInterventie: w.dataInterventie,
          createdAt: w.createdAt?.toDate?.()?.toISOString?.() ?? null,
          updatedAt: w.updatedAt?.toDate?.()?.toISOString?.() ?? str(w.updatedAt),
          createdBy: w.createdBy,
          createdByName: w.createdByName,
          autoGenerated: w.autoGenerated,
          statusLucrare: w.statusLucrare,
          equipmentIds: w.equipmentIds,
          equipmentStatus: w.revision?.equipmentStatus,
          checklistVersionId: w.revision?.checklistVersionId,
          revisionEquipmentTimes: w.revisionEquipmentTimes,
        },
        null,
        2,
      ),
    )

    const auditSnap = await db.collection("auditEvents").where("entityId", "==", w.id).get()
    const events = auditSnap.docs
      .map((d) => d.data() as any)
      .sort((a, b) => (a.occurredAt?.toMillis?.() ?? 0) - (b.occurredAt?.toMillis?.() ?? 0))
    console.log(`  --- audit: ${events.length} evenimente`)
    for (const e of events) {
      const when = e.occurredAt?.toDate?.()?.toISOString?.() ?? "?"
      const changes = Array.isArray(e.changes) ? e.changes : []
      console.log(`  - ${when} | ${e.actorName || e.actorId} | ${e.action} | câmpuri: ${changes.map((c: any) => c.field).join(", ") || "(niciunul)"}`)
      for (const c of changes) {
        if (!/equipment|revision/i.test(String(c.field))) continue
        console.log(`      ${c.field} before: ${String(c.before ?? "").slice(0, 800)}`)
        console.log(`      ${c.field} after:  ${String(c.after ?? "").slice(0, 800)}`)
      }
    }
  }
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
